variables:
  VITE_APP_VERSION: $CI_COMMIT_SHA

build_website:
  image: node:22-alpine
  stage: build
  script:
    - node --version
    - npm --version
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/

aws_s3:
  stage: .pre
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
