stages:
  - build
  - package
  - deploy

variables:
  VITE_APP_VERSION: $CI_COMMIT_SHA

build_website:
  image: node:22-alpine
  stage: build
  script:
    - node --version
    - npm --version
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/

build_docker_image:
  image:
    name: amazon/aws-cli:2.35.8
    entrypoint: [""]
  stage: package
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  before_script:
    - dnf install -y docker
  script:
    - aws --version
    - docker version
    - docker build -t $DOCKER_REGISTRY/gitlap-app-aws-ecr:$VITE_APP_VERSION .
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/gitlab-app-aws-ecr:$VITE_APP_VERSION



ecs_deploy:
  stage: deploy
  image: 
    name: amazon/aws-cli:2.35.8
    entrypoint: [""]
  script:
    - aws --version
    - aws ecs register-task-definition --cli-input-json file://aws/gitlab-prod.json
    - aws ecs update-service --cluster cluster-gitlab-1 --service Learn-Gitlab-app-Prod-service-9d4gfr69 --task-definition Learn-Gitlab-app-Prod
    #- aws ecs wait services-stable --cluster cluster-gitlab-1 --services Learn-Gitlab-app-Prod-service-9d4gfr69

